### ISSUE TITLE
Path to nmap is invalid

### ISSUE THREAD

**Issue by PNP-MA** [coj337/Nmap.NET#1]
Unhandled exception. System.ApplicationException: Path to nmap is invalid
   at Nmap.NET.NmapContext.Run()
   at Nmap.NET.Scanner.PortScan(ScanType scanType)
   at Program.Main(String[] args) in C:\Users\mratr\source\repos\LearningC#\LearningC#\Program.cs:line 15

I HAVE NMAP INSTALLED AND ADDED TO PATH STILL GETTING ERROR INVALID PATH

**Comment by UtopiaCloud** [comment]
i guess you need to put the nmap.exe in your project/build directory
